# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: rushikesh9.2004@gmail.com
author_name: rushikesh2k04
contract_name: Algonest
preset_name: starter
project_name: Algonest

